name: 'Install luarocks packages with using cache'
description: ''

inputs:

  packages:
    description: 'comma separated package names'
    required: true

runs:
  using: "composite"
  steps:

    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
      if: ${{ runner.os == 'macOS' }}

    - id: luarocks
      run: python ${TARGET_SCRIPT} ${PACKAGES}
      shell: bash
      env:
        TARGET_SCRIPT: ${{ github.action_path }}/output_config.py
        PACKAGES: ${{ inputs.packages }}

    - uses: actions/cache@v3
      with:
        path: |
          ${{ steps.luarocks.outputs.rocks_tree1 }}
          ${{ steps.luarocks.outputs.rocks_tree2 }}
        key: |
          ${{ runner.os }}-luarocks-rocks-trees-${{ steps.luarocks.outputs.program_version }}-${{ steps.luarocks.outputs.versions_hash }}

    - run: python ${TARGET_SCRIPT} ${PACKAGES}
      shell: bash
      env:
        TARGET_SCRIPT: ${{ github.action_path }}/install.py
        PACKAGES: ${{ inputs.packages }}
