name: Neovim plugin CI
on:
  workflow_call:
    inputs:
      test_os:
        description: "`runs-on` on test job"
        required: false
        default: '["ubuntu-latest", "macos-latest", "windows-latest"]'
        type: string
  workflow_dispatch:
  push:
    paths:
      - Makefile
      - .github/workflows/neovim-plugin-ci.yml

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.test_os || '["ubuntu-latest", "macos-latest", "windows-latest"]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: notomo/action-setup-nvim-lua@v1

      - id: luarocks
        run: |
          import subprocess
          home_tree_result = subprocess.run(
              ["luarocks", "config", "home_tree"], stdout=subprocess.PIPE, shell=True
          )
          home_tree = home_tree_result.stdout.decode("utf-8")
          print(f"::set-output name=home_tree::{home_tree}")

          program_version_result = subprocess.run(
              ["luarocks", "config", "program_version"], stdout=subprocess.PIPE, shell=True
          )
          program_version = program_version_result.stdout.decode("utf-8")
          print(f"::set-output name=program_version::{program_version}")
        shell: python

      - uses: actions/cache@v3
        with:
          path: ${{ steps.luarocks.outputs.home_tree }}
          key: ${{ runner.os }}-luarocks-tree-${{ steps.luarocks.outputs.version }}

      - run: luarocks install vusted

      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - run: make test
        env:
          VUSTED_NVIM: ${{ steps.vim.outputs.executable }}
